---
title: "Reading List for LAWS20441"
author: "Reka Solymosi"
date: "21/08/2017"
output:
  html_document:
    toc: true
---

This is the reading that should be done for each lecture **before you attend the lab session**. Please please please do this reading before you come to the lab in order to make the most of the lab time. It will help if you are alread familiar with the concepts when you begin to apply them. They are not long, some of them are videos, and almost all of them are available online with your library login. There is literally no way of making this easier to access and read, short of reading it out loud to you. The links should send you directly to the relevant reading, although you will have to log in with your university username and password. 


If you want to read something cover to cover, I would recommend [Tiger That Isn`t, written by Michael Blastland & Andrew Dilnot.](https://www.dawsonera.com/abstract/9781847650795). Very easy, very light, and will give you a good feeling about stats (I hope). I will also put other recommended reading at the end of this list. 


#Mandatory reading for *before* the session


##Week 1. Data sets & variables
	
- Watch: [Hans Rosling The Joy of Stats](http://www.gapminder.org/videos/the-joy-of-stats/)
- Chapter 1 (p.1-5): [The Tiger that Isn't](https://www.dawsonera.com/readonline/9781847650795)
- Chapter 1 (p.1-7): [Statistical Methods for the Social Sciences: Pearson New International Edition](https://www.dawsonera.com/readonline/9781292034898)
- Chapter 2 (p.13-27): [Statistics in Criminal Justice](https://link.springer.com/chapter/10.1007/978-1-4614-9170-5_2) (not the exercises)


##Week 2. Describing and visualising single variables

- Chapter 5, (p.68-87): [The tiger that isn't](https://www.dawsonera.com/readonline/9781847650795)
- Chapter 5: (p.61-78): [Just plain data analysis](https://www.dawsonera.com/readonline/9781442215092)
- Chapter 3 (p.31-61): [Statistical Methods for the Social Sciences: Pearson New International Edition](https://www.dawsonera.com/readonline/9781292034898).

##Week 3. Making comparisons I: the basics

- Chapters 2 and 3 (p.6-36): [The Tiger that Isn't](https://www.dawsonera.com/readonline/9781847650795) 
- Chapter 3 (p.36-64): [Statistics in Criminal Justice](https://link.springer.com/chapter/10.1007/978-1-4614-9170-5_3)

##Week 4. Concepts, operationalisation, measurement, and Sampling

- Chapters 6 and 8 (p.88-106 and 124-146): [The Tiger tht Isn't](https://www.dawsonera.com/readonline/9781847650795)
- Chapters 5 and 6 (p.123-196): [The Practice of Social Research, International Edition](https://www.dawsonera.com/abstract/9781408093153)
- Chapters 4 and 5 (p.65-124) in [Statistics in Criminal Justice](https://link.springer.com/book/10.1007%2F978-1-4614-9170-5)
- Chapter 2 (p.11-25): [Statistical Methods for the Social Sciences: Pearson New International Edition](https://www.dawsonera.com/readonline/9781292034898).

##Week 5. Making comparisons II: the relevance of research design

- Chapter 4 (p.88-122): [The Practice of Social Research, International Edition](https://www.dawsonera.com/abstract/9781408093153).
- Chapter 1 (p.1-22): [Just Plain Data Analysis](https://www.dawsonera.com/readonline/9781442215092) 
- Chapter 1 and half of 2 (p.1-21): [Principles of Applied Statistics](https://www.cambridge.org/core/books/principles-of-applied-statistics/E7225E64F86B2C8193CA3C57621B6338) (stop after section 2.3)

##Week 6. Data visualisation
- Watch: [David Mccandless on the beauty of data visualisation](https://www.ted.com/talks/david_mccandless_the_beauty_of_data_visualization) 
- Chapters 1 and 2 (p.27-65) [The Truthful Art by Alerto Cairo](https://www.vlebooks.com/vleweb/Product/Index/819451?page=0)

##Week 7. Looking at trends


- Chapter 13 (p.95-102)['Models Are Stories Are Not Real Life' in Statistics in Society]()

- [Read this ONS report on the seasonality of crime](www.ons.gov.uk/ons/guide-method/method-quality/specific/crime-statistics-methodology/methodological-note--seasonality-of-property-crime.pdf) - download link
- Chapter 14: Time (p.407-449) [Grammar of Graphics](https://link-springer-com.manchester.idm.oclc.org/chapter/10.1007/0-387-28695-0_14)
- This paper on [Crime seasonality and its variations across space](http://www.sciencedirect.com/science/article/pii/S0143622813001410)

##Week 8. Qualitative data
- TBD

##Week 9. Qualitative data analysis
- TBD

##Week 10. Wrap up and project support




