---
title: "Week 1 Tasks"
author: "Reka Solymosi"
date: "25/08/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Tasks


1.) Ensure you understand the levels of measurement for variables (at least nominal, ordinal, numeric). 

<!--
Qs:

The variable fear of crime is collected by asking people to respond to a question about how worried they are about becoming a victim of burglary. They can choose from the following answers: Very worried, Fairly worried, Not very worried, Not at all worried. 
This variable is
Nominal, Ordinal, Numeric


The variable trust in police is collected by asking people to respond to a question about how good of a job they believe police to be doing in their area. They can choose from the following answers: Very good job, Fairly good job, Not a very good job, Not at all a good job. 
This variable is
Nominal, Ordinal, Numeric


The variable gender is collected by asking people to respond to a question about whethery they are male or female.  
This variable is
Nominal, Ordinal, Numeric


The variable age is collected by asking people to respond to a question about which age categori they belong to: under 16, 16 - 25, 25 - 35, 35 - 45, 45 - 55, or 55 and over.  
This variable is
Nominal, Ordinal, Numeric


The variable ethnicity is collected by asking people to respond to a question about their ethnicity.  
This variable is
Nominal, Ordinal, Numeric


The population of a neighbourhood is measured using data from the 2011 UK census, which counted the number of people who live in each neighbourhood. The variable of the population of each neighbourhood is
Nominal, Ordinal, Numeric






-->


 2.) Find the data dictionary for the [police.uk](https://data.police.uk/) data, and copy it into a word document. 
 
 
  <!-- 
 
 Qs:
 
"Falls within" is a variable in the police.uk data set. What force does this variable record?
A: The force that provided the data about the crime. 
B: The force who first responded to the incident. 
C: The force who's juristriction the crime incident fell under.
D: The force who investigated the crime.


"Falls within" is a variable within the police.uk data set. At present, also the force that provided the data about the crime. This is currently being looked into and is likely to change in the near future. Is this True or False?
T/F

"Longitude and Latitude" are variables within the police.uk data set. What are these coordinates of?
A: the location where the 999 call was made
B: the location where the police officer noted in the crime report
C: the approximate location of a crime — not the exact place that it happened
D: the home address of the offender charged with the crime


"Longitude and Latitude" are variables within the police.uk data set. These coordinates provide an exact, point-level location of where the crime occurred, accurate to the nearest 5 meter radius. Is this True or False?
T/F



-->
 
 
 3.) Download the .xls data file about Domestic abuse in England and Wales from [here](https://www.ons.gov.uk/peoplepopulationandcommunity/crimeandjustice/datasets/domesticabuseinenglandandwalesbulletintables). Open it up in Excel, and select the sheet that is titled **Figure 2** (*Proportion of adults aged 16 to 59 who experienced domestic abuse in the last year, by sex and age group, three year combined dataset, April 2013 to March 2016 CSEW*). Tidy this data set, so that you have three variables, which are: *age group*, *gender*, and *% victims once or more*. Copy your new table that you have created into the same word document where you also saved the police.uk data dictionary.  
 
 <!-- 
 
 Qs:
 
What group (gender and age) were the least victimised, at 2.2%? (men 55 to 59)
What group (gender and age) were the most victimised, at 11.9%? (women 16 to 19)
What group (gender and age) were the second most victimised, at 9.2%? (women 20 to 24)
What group (gender and age) were the second least victimised, at 3.8%? (men 50 to 54)
How many observations (rows) are there in this data set? (18)
-->
 
 
4.) Make sure you have completed the reading on the list. 